int8_t uint8_t
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/dews/anaconda3/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/dews/Scrivania/CC4CS/src/__init__.py", line 174, in callback
    inptGen.createHeaders(chosenParams, currentType, currentIndex)
  File "/home/dews/Scrivania/CC4CS/src/InputsGenerator.py", line 136, in createHeaders
    frstSize, scndSize = sizes
ValueError: not enough values to unpack (expected 2, got 0)
